/**
 * Turn `data/site/redirects.json` into `dist/client/_redirects`.
 *
 * The rename path in the write pipeline records `/product/{old} → /product/{new}` in that file as
 * part of the same commit that moves the product (Requirement 12.11). Turning those entries into
 * real 301s has to happen at the edge rather than in the Worker, because the old URL is a
 * prerendered-HTML address: Cloudflare's asset store answers it (with a 404) without ever invoking
 * the Worker, so `src/middleware.ts` never sees the request in production. `_redirects` is the
 * mechanism the asset store itself honours, and it is consulted before the 404.
 *
 * `src/middleware.ts` implements the identical rule for the routes the Worker *does* serve and for
 * `astro dev`. Both read the same file; neither is a copy of the other's list.
 *
 * Trailing-slash normalisation is not written here — `html_handling = "drop-trailing-slash"` in
 * `wrangler.toml` is the platform's own switch for it, and enumerating every path would be a
 * generated list that goes stale the moment a page is added.
 *
 * Runs in `postbuild`. Writing the file unconditionally (rather than only when there are entries)
 * keeps the deployed artifact set the same shape on every build.
 *
 * Design: SEO and Structured Data → URLs, sitemap, robots; Deployment.
 * Requirements: 12.11, 23.15, 23.16.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SOURCE = join(ROOT, 'data', 'site', 'redirects.json');
const OUTPUT = join(ROOT, 'dist', 'client', '_redirects');

const HEADER = [
  '# Generated by scripts/emit-redirects.ts from data/site/redirects.json — do not edit.',
  '# Each line is a 301 for a slug that has been renamed (Requirement 12.11).',
];

/** `/from /to 301`, one per entry, in a stable order so the artifact is reproducible. */
export function renderRedirects(map: Readonly<Record<string, string>>): string {
  const lines = Object.entries(map)
    .filter(([from, to]) => from.startsWith('/') && to.startsWith('/') && from !== to)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([from, to]) => `${from} ${to} 301`);
  return [...HEADER, ...lines, ''].join('\n');
}

async function main(): Promise<void> {
  const raw = JSON.parse(await readFile(SOURCE, 'utf8')) as Record<string, string>;
  const body = renderRedirects(raw);
  await writeFile(OUTPUT, body, 'utf8');
  const count = body.split('\n').filter((line) => line.endsWith(' 301')).length;
  console.log(
    `[emit-redirects] wrote dist/client/_redirects with ${count} redirect(s) from data/site/redirects.json`,
  );
}

const invokedDirectly =
  process.argv[1] !== undefined && process.argv[1].endsWith('emit-redirects.ts');
if (invokedDirectly) {
  await main();
}
