/**
 * Content gate — runs in CI before the type check and again before the build.
 *
 * Every JSON file under `data/` is validated against the schema that owns its
 * path, and each failure is reported as `file → field.path: message`. Three
 * cross-file rules that no single-file schema can express are checked here too:
 *
 * 1. A product's `category` must resolve to an existing `data/categories/*.json`
 *    (requirement 18.5) — otherwise the product would be unreachable by any route.
 * 2. A product's (and category's) filename must equal its `slug`, because the
 *    filename *is* the slug (design → Data Models → File layout rules). A mismatch
 *    means the URL and the file disagree.
 * 3. A file in a location no schema claims is a failure, not a silent pass — a
 *    typo'd directory must not smuggle unvalidated content into the repo.
 *
 * Exit contract: 0 when everything validates, 1 otherwise, with every problem
 * printed. Nothing is written or repaired.
 *
 * Design: Data Models → File layout rules; Testing Strategy → CI gates.
 * Requirements: 17.1, 17.7, 17.8, 18.5, 26.11, 28.3.
 *
 * Usage: npm run validate:content [-- <directory>]
 */

import { readdir, readFile, stat } from 'node:fs/promises';
import { join, relative, resolve, sep } from 'node:path';

import { CategorySchema } from '../src/schemas/category.ts';
import { HomepageSchema } from '../src/schemas/homepage.ts';
import { ProductSchema } from '../src/schemas/product.ts';
import { RankingsSchema } from '../src/schemas/rankings.ts';
import { ReviewSchema } from '../src/schemas/review.ts';
import { RedirectsSchema, SiteSettingsSchema } from '../src/schemas/site.ts';

export interface ValidationFailure {
  readonly file: string;
  /** Dotted field path, or `<file>` when the whole file is unreadable. */
  readonly path: string;
  readonly message: string;
}

/** Anything with a `safeParse` — every schema in `src/schemas`. */
interface Validatable {
  safeParse(input: unknown): {
    success: boolean;
    data?: unknown;
    error?: { issues: readonly { path: readonly PropertyKey[]; message: string }[] };
  };
}

async function* walk(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else if (entry.isFile()) {
      yield full;
    }
  }
}

type Kind = 'product' | 'category' | 'review' | 'site' | 'snapshot';

interface Route {
  readonly kind: Kind;
  readonly schema: Validatable;
  /** True when the filename stem must equal the record's `slug`. */
  readonly filenameIsSlug: boolean;
}

/** Generated by the analytics cron, not hand-authored; its schema lands with task 20. */
const SnapshotSchema: Validatable = {
  safeParse: (input: unknown) =>
    typeof input === 'object' && input !== null && !Array.isArray(input)
      ? { success: true, data: input }
      : {
          success: false,
          error: { issues: [{ path: [], message: 'snapshot must be a JSON object' }] },
        },
};

/** Which schema owns which path. A path no entry claims is a failure. */
function routeFor(relativePath: string): Route | null {
  const parts = relativePath.split(sep);
  const [dir, ...rest] = parts;
  if (dir === undefined || rest.length !== 1) return null;
  const file = rest[0] as string;

  switch (dir) {
    case 'products':
      return { kind: 'product', schema: ProductSchema, filenameIsSlug: true };
    case 'categories':
      return { kind: 'category', schema: CategorySchema, filenameIsSlug: true };
    case 'reviews':
      return { kind: 'review', schema: ReviewSchema, filenameIsSlug: false };
    case 'snapshots':
      return { kind: 'snapshot', schema: SnapshotSchema, filenameIsSlug: false };
    case 'site':
      switch (file) {
        case 'settings.json':
          return { kind: 'site', schema: SiteSettingsSchema, filenameIsSlug: false };
        case 'homepage.json':
          return { kind: 'site', schema: HomepageSchema, filenameIsSlug: false };
        case 'rankings.json':
          return { kind: 'site', schema: RankingsSchema, filenameIsSlug: false };
        case 'redirects.json':
          return { kind: 'site', schema: RedirectsSchema, filenameIsSlug: false };
        default:
          return null;
      }
    default:
      return null;
  }
}

function stem(relativePath: string): string {
  const name = relativePath.split(sep).pop() ?? relativePath;
  return name.replace(/\.json$/, '');
}

interface ParsedFile {
  readonly file: string;
  readonly route: Route;
  readonly value: Record<string, unknown>;
}

function validateFile(
  relativePath: string,
  raw: string,
): { failures: ValidationFailure[]; parsed?: ParsedFile } {
  const route = routeFor(relativePath);
  if (route === null) {
    return {
      failures: [
        {
          file: relativePath,
          path: '<file>',
          message:
            'no schema owns this path — content lives in data/{products,categories,reviews}/*.json, ' +
            'data/site/{settings,homepage,rankings,redirects}.json, or data/snapshots/*.json',
        },
      ],
    };
  }

  let value: unknown;
  try {
    value = JSON.parse(raw);
  } catch (error) {
    return {
      failures: [
        {
          file: relativePath,
          path: '<file>',
          message: error instanceof Error ? error.message : 'unparseable JSON',
        },
      ],
    };
  }

  const result = route.schema.safeParse(value);
  if (!result.success) {
    const issues = result.error?.issues ?? [];
    return {
      failures: issues.map((issue) => ({
        file: relativePath,
        path: issue.path.length > 0 ? issue.path.map((p) => String(p)).join('.') : '<root>',
        message: issue.message,
      })),
    };
  }

  const record = result.data as Record<string, unknown>;
  const failures: ValidationFailure[] = [];

  if (route.filenameIsSlug) {
    const slug = record['slug'];
    if (typeof slug === 'string' && slug !== stem(relativePath)) {
      failures.push({
        file: relativePath,
        path: 'slug',
        message: `slug "${slug}" must equal the filename "${stem(relativePath)}" — the filename is the slug`,
      });
    }
  }

  return { failures, parsed: { file: relativePath, route, value: record } };
}

/** Cross-file rules: a product's category must be a category that exists. */
function validateReferences(parsed: readonly ParsedFile[]): ValidationFailure[] {
  const categorySlugs = new Set(
    parsed
      .filter((entry) => entry.route.kind === 'category')
      .map((entry) => String(entry.value['slug'])),
  );

  const failures: ValidationFailure[] = [];
  for (const entry of parsed) {
    if (entry.route.kind !== 'product') continue;
    const category = String(entry.value['category']);
    if (!categorySlugs.has(category)) {
      const known = [...categorySlugs].sort().join(', ') || '<none>';
      failures.push({
        file: entry.file,
        path: 'category',
        message: `category "${category}" has no data/categories/${category}.json (known: ${known})`,
      });
    }
  }
  return failures;
}

export async function validateContent(root: string): Promise<ValidationFailure[]> {
  const failures: ValidationFailure[] = [];
  const parsed: ParsedFile[] = [];
  let checked = 0;

  for await (const file of walk(root)) {
    if (!file.endsWith('.json')) continue;
    checked += 1;
    const result = validateFile(relative(root, file), await readFile(file, 'utf8'));
    failures.push(...result.failures);
    if (result.parsed !== undefined) parsed.push(result.parsed);
  }

  failures.push(...validateReferences(parsed));

  if (failures.length === 0) {
    const products = parsed.filter((p) => p.route.kind === 'product').length;
    const categories = parsed.filter((p) => p.route.kind === 'category').length;
    console.log(
      `validate:content — ${checked} file(s) valid under ${relative(process.cwd(), root) || root}/ ` +
        `(${products} product(s), ${categories} category/categories).`,
    );
  }
  return failures;
}

async function main(): Promise<void> {
  const target = resolve(process.argv[2] ?? 'data');

  try {
    const info = await stat(target);
    if (!info.isDirectory()) throw new Error('not a directory');
  } catch {
    console.error(`validate:content — content directory not found: ${target}`);
    process.exitCode = 1;
    return;
  }

  const failures = await validateContent(target);
  if (failures.length === 0) return;

  console.error(`validate:content — FAILED with ${failures.length} problem(s):`);
  for (const failure of failures) {
    console.error(`  ${failure.file} → ${failure.path}: ${failure.message}`);
  }
  process.exitCode = 1;
}

const invokedDirectly =
  process.argv[1] !== undefined && process.argv[1].endsWith('validate-content.ts');
if (invokedDirectly) {
  await main();
}
